function plot_state_space(param, P, t)

figure()
title('State Space')
grid on
axis equal

if param.Nd == 2
    
    P_a = zeros(param.Nd, param.Na, length(t));
    for i = 1:param.Na
        P_a(:,i,:) = P(:,i,:);
    end
    centroid_P = mean(P_a,2); %param.my_1'*P_a;
    plot( squeeze(centroid_P(1,:)), squeeze(centroid_P(2,:)),...
        'color', param.color_c, 'linewidth',param.linewidth);
    
    for i = 1:param.Na
        plot( squeeze(P(1,i,:)), squeeze(P(2,i,:)), ...
            'color',    param.color_a,...
            'linewidth',param.linewidth)
        plot( squeeze(P(1,i,1)), squeeze(P(2,i,1)), ...
            'color', param.color_a, ...
            'Marker',param.marker_start, ...
            'MarkerSize', param.markersize)
        plot( squeeze(P(1,i,end)), squeeze(P(2,i,end)), ...
            'color', param.color_a, ...
            'Marker',param.marker_stop, ...
            'MarkerSize', param.markersize)
    end
    
    for i = param.Na+1:param.N
        plot( squeeze(P(1,i,:)), squeeze(P(2,i,:)), ...
            'color',    param.color_b,...
            'linewidth',param.linewidth)
        plot( squeeze(P(1,i,1)), squeeze(P(2,i,1)), ...
            'color', param.color_b, ...
            'Marker',param.marker_start, ...
            'MarkerSize', param.markersize)
        plot( squeeze(P(1,i,end)), squeeze(P(2,i,end)), ...
            'color', param.color_b, ...
            'Marker',param.marker_stop, ...
            'MarkerSize', param.markersize)
    end
    
    plot( param.xd(1,:), param.xd(2,:), 'color',param.color_d,...
        'linewidth',param.linewidth)
end

h1 = plot(nan,nan,'color',param.color_a,'linewidth',param.linewidth);
h2 = plot(nan,nan,'color',param.color_b,'linewidth',param.linewidth);
h3 = plot(nan,nan,'color',param.color_d,'linewidth',param.linewidth);
h4 = plot(nan,nan,'color',param.color_c,'linewidth',param.linewidth);
legend([h1,h2,h3,h4],'Free','Input','Desired','Centroid','location','best');
set(gca,'fontsize',param.fontsize)

end